kafka_consumer:
  topic: web_monitor_topic
  bootstrap_servers: localhost:9092
  group_id: web_monitor_group_1

postgre_sql:
  host: 127.0.0.1
  port: 5432
  dbname: web_monitoring
  user: web_monitoring
  password: 12345