kafka_consumer:
  topic: web_monitor_topic
  bootstrap_servers: localhost:9092
  group_id: web_monitor_group_1

postgre_sql:
  connecton:
    host: 127.0.0.1
    port: 5432
    dbname: web_monitoring
    user: web_monitoring
    password: 12345
  reconnect:
    tries: 5
    delay: 1
    backoff: 2