kafka_consumer:
  topic: web_monitor_topic
  sleep_interval: 5
  connection:
    bootstrap_servers: broker:9092
    group_id: web_monitor_group_1
    consumer_timeout_ms: 10000

postgre_sql:
  connection:
    host: pg-web-monitoring-esenenkova-c5b9.aivencloud.com
    port: 20891
    dbname: web-monitoring
    user: avnadmin
    password:
  reconnect:
    tries: 5
    delay: 1
    backoff: 2
