web_monitoring:
  check_frequency: 30
  source_filename: web_monitor/data/url_list.json
  conn_timeout: 5

# should be replaced with aiven kafka
kafka_producer:
  topic: web_monitor_topic
  connection:
    bootstrap_servers: broker:9092
